version: "3"
networks:
  proxynet:
    external:
      name: authapp.network
services:
  authapp_api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: authapp_api
    container_name: authapp_api
    restart: unless-stopped
    networks:
      - proxynet
    ports:
      - "9090:9090"
  authapp_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    container_name: authapp_db
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    networks:
      - proxynet
    ports:
      - "9091:3306"
    environment:
      TZ: Africa/Nairobi
      MYSQL_ROOT_PASSWORD: "_y$ecPdD(6HVNXYZ^;u3"
      MYSQL_DATABASE: "authapp_db"
      MYSQL_USER: "authapp_api"
      MYSQL_PASSWORD: "_y$ecPdD(6HVNXYZ^;u3"
  authapp_minio:
    image: minio/minio
    container_name: authapp_minio
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server --address 0.0.0.0:9000 /data